name: Hello CI
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from a robot computer!"
      - name: Pretend tests
        run: |
          echo "Running tests..."
          exit 1
      - name: Show where we are
        run: |
          echo "Commit ID: $GITHUB_SHA"
          echo "Branch: $GITHUB_REF_NAME"
